sudo: required
services:
    - docker

before_install:
  - docker build -t simmonson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true simmonson/react-test npm run test -- --coverage

after_success:
  - docker build -t simmonson/multi-client ./client
  - docker build -t simmonson/multi-nginx ./nginx
  - docker build -t simmonson/multi-server ./server
  - docker build -t simmonson/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push them to docker hub
  - docker push simmonson/multi-client
  - docker push simmonson/multi-nginx
  - docker push simmonson/multi-server
  - docker push simmonson/multi-worker
