sudo: required
services:
    - docker

before_install:
  - docker build -t simmonson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run simmonson/react-test npm test -- --coverage

after_success:
  - docker build -t simmonson/multi-client ./client
  - docker build -t simmonson/multi-nginx ./nginx
  - docker build -t simmonson/multi-server ./server
  - docker build -t simmonson/multi-worker ./worker